{% set name = "tclap" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mirror/tclap/archive/v{{ version }}.tar.gz
  sha256: c398eaadab187257cb90d10607e3b67894e502b50d4a6eafeea1a9aa1a372925

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - autoconf
    - m4
    - pkgconfig


test:
  commands:
    - test -d ${PREFIX}/include/tclap


about:
  home: http://tclap.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: TCLAP is a small, flexible library that provides a simple interface for defining and accessing command line arguments.
  doc_url: http://tclap.sourceforge.net/manual.html
  dev_url: https://sourceforge.net/projects/tclap/

extra:
  recipe-maintainers:
    - marcelotrevisani
